import React from 'react'
import Auth from '../components/profile/Auth'
import Header from '../components/home/header'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const auth = () => {
    return (
        <div className={styles.container}>
        <Head>
          <title>XTELPT</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='bg-[#252525] h-full w-full flex-1'>
            <Header />
            <Auth />
        </div>
        </div>
      )
}

export default auth