import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/home/header'
import Main from '../components/home/main'
import Footer from '../components/home/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>XTELPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#252525]  h-full w-full flex-1'>
        <Header />
        <Main />
        <Footer />
      </div>
    </div>
  )
}
