import { ethers } from 'ethers';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React, { useContext, useEffect, useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Modal from 'react-modal';
import Header from '../components/home/header';
import { abi } from '../constants';
import { XContext } from '../context/XContext';
import styles from '../styles/Home.module.css'


const NewModal = () => {
  const router = useRouter()
  const text = router.query.text
  const type = router.query.type

  const [hostSearch, setHostSearch] = useState()
  const [camp, setCamp] = useState()

  const { xtelptAddress } = useContext(XContext)

  const updateUIValues = async () => {
    if (type == "Host") {
      const provider = new ethers.providers.Web3Provider(window.ethereum)
      const xtelptContract = new ethers.Contract(xtelptAddress, abi, provider)

      const allHost = await xtelptContract.getAllAccount()
      console.log(allHost)

      let arr = []

      for (let i = 0; i < allHost.length; i++) {
        let prof = await xtelptContract.getProfile(allHost[i])
        console.log(prof.name.toLowerCase() == text.toLowerCase())
        if (prof.name.toLowerCase() == text.toLowerCase()) {
          arr.push(prof)
        }
      }

      console.log("arr", arr)

      setHostSearch(arr)
    }

    if (type == "campaign") {

    }
  }


  useEffect(() => {
    setTimeout(() => {
      updateUIValues()
    }, 1000);
  }, [type, text])


  return (
    <div className={styles.container}>
      <Head>
        <title>XTELPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#252525] h-screen w-full flex-1'>
        <Header />

        <div class="flex justify-center flex-col items-center gap-5 mt-20">
          <h1 className='text-2xl text-center text-white font-bold'>Search Result</h1>

          {hostSearch?.map((item) => (
            <div key={`${item?.addr}`} className='flex justify-center pb-10 w-full '>
              <div className='bg-[#2D1300] w-1/2 h-full shadow-[0_6px_10px_4px_rgba(0,0,0,0.5)] rounded-[30px] '>
                <div className='flex justify-between p-6 '>
                  <div className='justify-start pl-6 font-noto font-semibold text-[#817C7C] w-34 text-12'>
                    <Image src={`https://gateway.pinata.cloud/ipfs/${item?.profilePic}`} height={50} width={50} className="rounded-full" />
                  </div>
                  <div className='justify-center items-center'><p className='justify-center items-center text-2xl text-red-400'>{item?.name} - <span className='text-white'>{item?.hostTitle}</span></p></div>
                  <div className=' items-center pr-7 justify-end'>
                    <div className=' text-white cursor-pointer font-noto rounded-[10px] h-[40px] w-[140px] text-center font-semibold bg-green-600  py-2 pl-5  text-[14px]'>
                      View Profile
                    </div>
                  </div></div>
              </div>
            </div>
          ))}
          {hostSearch?.length == 0 && (

            <div className='flex justify-center pb-10 w-full '>
              <div className='bg-[#2D1300] w-1/2 h-full shadow-[0_6px_10px_4px_rgba(0,0,0,0.5)] rounded-[30px] '>
                <div className='flex justify-between p-6 '>

                  <div className='justify-center items-center'><p className='justify-center text-center items-center text-2xl  text-white'>Nothing to Show Here</p></div>
                  <div className=' items-center pr-7 justify-end'>

                  </div></div>
              </div>
            </div>
          )}

        </div>

      </div>
    </div>

  );
}

export default NewModal