import React, { useContext } from 'react'
import Header from '../components/home/header'
import Addschedule from './addschedule'
import Checkschedule from './checkschedule'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { XContext } from '../context/XContext'

const checkSchedule = () => {
  const { currentAccount, me } = useContext(XContext)
  return (
    <div className={styles.container}>
      <Head>
        <title>XTELPT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#252525] h-screen w-full flex-1'>
        <Header />


        <Checkschedule />

      </div>
    </div>
  )
}

export default checkSchedule